source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '14.0'
use_frameworks!

target 'BCAD_Example' do
  pod 'BCAD', :path => '../'
  
end
